/**
 * Swagger Petstore - OpenAPI 3.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  lazy,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { Category, categorySchema } from './category';
import { Status1Enum, status1EnumSchema } from './status1Enum';
import { Tag, tagSchema } from './tag';

export interface Pet {
  id?: bigint;
  name: string;
  category?: Category;
  photoUrls: string[];
  tags?: Tag[];
  /** pet status in the store */
  status?: Status1Enum;
}

export const petSchema: Schema<Pet> = object({
  id: ['id', optional(bigint())],
  name: ['name', string()],
  category: ['category', optional(lazy(() => categorySchema))],
  photoUrls: ['photoUrls', array(string(), { xmlItemName: 'photoUrl' })],
  tags: [
    'tags',
    optional(array(lazy(() => tagSchema), { xmlItemName: 'tag' })),
  ],
  status: ['status', optional(status1EnumSchema)],
});
