/**
 * Swagger Petstore - OpenAPI 3.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for StatusEnum
 */
export enum StatusEnum {
  Placed = 'placed',
  Approved = 'approved',
  Delivered = 'delivered',
}

/**
 * Schema for StatusEnum
 */
export const statusEnumSchema: Schema<StatusEnum> = stringEnum(StatusEnum);
